export const leaderboard = {
  rows: [
    {
      player_id: 102088,
      player_name: "Rory Mcilroy",
      position: 1,
      movement: 0,
      num_events: 8,
      num_wins: 2,
      points: "4958.34",
      num_top_tens: 6,
    },
    {
      player_id: 123640,
      player_name: "Jon Rahm",
      position: 2,
      movement: 0,
      num_events: 5,
      num_wins: 1,
      points: "2608.64",
      num_top_tens: 3,
    },
    {
      player_id: 111169,
      player_name: "Adrian Meronk",
      position: 3,
      movement: 0,
      num_events: 19,
      num_wins: 2,
      points: "1993.19",
      num_top_tens: 6,
    },
    {
      player_id: 122584,
      player_name: "Victor Perez",
      position: 4,
      movement: 0,
      num_events: 15,
      num_wins: 1,
      points: "1930.52",
      num_top_tens: 2,
    },
    {
      player_id: 125002,
      player_name: "Min Woo Lee",
      position: 5,
      movement: 1,
      num_events: 12,
      num_wins: 0,
      points: "1876.57",
      num_top_tens: 5,
    },
    {
      player_id: 112771,
      player_name: "Alexander Björk",
      position: 6,
      movement: -1,
      num_events: 19,
      num_wins: 0,
      points: "1822.69",
      num_top_tens: 8,
    },
    {
      player_id: 130876,
      player_name: "Vincent Norrman",
      position: 7,
      movement: 35,
      num_events: 4,
      num_wins: 2,
      points: "1753.35",
      num_top_tens: 2,
    },
    {
      player_id: 123697,
      player_name: "Robert Macintyre",
      position: 8,
      movement: -1,
      num_events: 20,
      num_wins: 0,
      points: "1667.14",
      num_top_tens: 6,
    },
    {
      player_id: 120460,
      player_name: "Viktor Hovland",
      position: 9,
      movement: -1,
      num_events: 6,
      num_wins: 0,
      points: "1545.58",
      num_top_tens: 2,
    },
    {
      player_id: 102271,
      player_name: "Joost Luiten",
      position: 10,
      movement: -1,
      num_events: 21,
      num_wins: 0,
      points: "1411.7",
      num_top_tens: 7,
    },
  ],
  pageCount: 15,
};

export const tour2season2021 = {
  rows: [
    {
      player_id: 151591,
      player_name: "Collin Morikawa",
      position: 1,
      movement: 0,
      num_events: 20,
      num_wins: 2,
      points: "2,171",
      num_top_tens: 8,
    },
    {
      player_id: 102154,
      player_name: "Jordan Spieth",
      position: 2,
      movement: 0,
      num_events: 22,
      num_wins: 1,
      points: "2,139",
      num_top_tens: 9,
    },
    {
      player_id: 106366,
      player_name: "Patrick Cantlay",
      position: 3,
      movement: 0,
      num_events: 21,
      num_wins: 2,
      points: "2,056",
      num_top_tens: 5,
    },
    {
      player_id: 102313,
      player_name: "Harris English",
      position: 4,
      movement: 0,
      num_events: 23,
      num_wins: 2,
      points: "2,039",
      num_top_tens: 8,
    },
    {
      player_id: 140926,
      player_name: "Jon Rahm",
      position: 5,
      movement: 0,
      num_events: 19,
      num_wins: 1,
      points: "2,003",
      num_top_tens: 12,
    },
    {
      player_id: 136594,
      player_name: "Abraham Ancer",
      position: 6,
      movement: 0,
      num_events: 24,
      num_wins: 1,
      points: "1,926",
      num_top_tens: 7,
    },
    {
      player_id: 143893,
      player_name: "Bryson DeChambeau",
      position: 7,
      movement: 0,
      num_events: 19,
      num_wins: 2,
      points: "1,910",
      num_top_tens: 7,
    },
    {
      player_id: 79003,
      player_name: "Louis Oosthuizen",
      position: 8,
      movement: 0,
      num_events: 19,
      num_wins: 0,
      points: "1,877",
      num_top_tens: 8,
    },
    {
      player_id: 100360,
      player_name: "Justin Thomas",
      position: 9,
      movement: 0,
      num_events: 20,
      num_wins: 1,
      points: "1,758",
      num_top_tens: 5,
    },
    {
      player_id: 142528,
      player_name: "Sam Burns",
      position: 10,
      movement: 0,
      num_events: 23,
      num_wins: 1,
      points: "1,721",
      num_top_tens: 7,
    },
  ],
  pageCount: 15,
};

export const tour2season2023 = {
  rows: [
    {
      player_id: 138154,
      player_name: "Scottie Scheffler",
      position: 1,
      movement: -1,
      num_events: 22,
      num_wins: 2,
      points: "4,218",
      num_top_tens: 16,
    },
    {
      player_id: 140167,
      player_name: "Viktor Hovland",
      position: 2,
      movement: -5,
      num_events: 22,
      num_wins: 2,
      points: "4,024",
      num_top_tens: 8,
    },
    {
      player_id: 84727,
      player_name: "Rory McIlroy",
      position: 3,
      movement: 0,
      num_events: 17,
      num_wins: 2,
      points: "3,494",
      num_top_tens: 12,
    },
    {
      player_id: 140926,
      player_name: "Jon Rahm",
      position: 4,
      movement: 3,
      num_events: 19,
      num_wins: 4,
      points: "3,486",
      num_top_tens: 10,
    },
    {
      player_id: 77716,
      player_name: "Lucas Glover",
      position: 5,
      movement: 1,
      num_events: 27,
      num_wins: 2,
      points: "3,041",
      num_top_tens: 5,
    },
    {
      player_id: 119947,
      player_name: "Max Homa",
      position: 6,
      movement: 0,
      num_events: 23,
      num_wins: 2,
      points: "2,871",
      num_top_tens: 11,
    },
    {
      player_id: 106366,
      player_name: "Patrick Cantlay",
      position: 7,
      movement: 2,
      num_events: 20,
      num_wins: 0,
      points: "2,843",
      num_top_tens: 9,
    },
    {
      player_id: 82948,
      player_name: "Brian Harman",
      position: 8,
      movement: -1,
      num_events: 26,
      num_wins: 1,
      points: "2,339",
      num_top_tens: 7,
    },
    {
      player_id: 155314,
      player_name: "Wyndham Clark",
      position: 9,
      movement: 1,
      num_events: 27,
      num_wins: 2,
      points: "2,157",
      num_top_tens: 7,
    },
    {
      player_id: 120310,
      player_name: "Matt Fitzpatrick",
      position: 10,
      movement: -30,
      num_events: 22,
      num_wins: 1,
      points: "2,043",
      num_top_tens: 5,
    },
  ],
  pageCount: 15,
};

export const noResults = { rows: [], pageCount: 0 };
