export const leaderboard = {
  rows: [
    {
      player_id: 102088,
      player_name: "Rory Mcilroy",
      position: 1,
      movement: 0,
      num_events: 8,
      num_wins: 2,
      points: "4958.34",
      num_top_tens: 6,
    },
    {
      player_id: 123640,
      player_name: "Jon Rahm",
      position: 2,
      movement: 0,
      num_events: 5,
      num_wins: 1,
      points: "2608.64",
      num_top_tens: 3,
    },
    {
      player_id: 111169,
      player_name: "Adrian Meronk",
      position: 3,
      movement: 0,
      num_events: 19,
      num_wins: 2,
      points: "1993.19",
      num_top_tens: 6,
    },
    {
      player_id: 122584,
      player_name: "Victor Perez",
      position: 4,
      movement: 0,
      num_events: 15,
      num_wins: 1,
      points: "1930.52",
      num_top_tens: 2,
    },
    {
      player_id: 125002,
      player_name: "Min Woo Lee",
      position: 5,
      movement: 1,
      num_events: 12,
      num_wins: 0,
      points: "1876.57",
      num_top_tens: 5,
    },
    {
      player_id: 112771,
      player_name: "Alexander Björk",
      position: 6,
      movement: -1,
      num_events: 19,
      num_wins: 0,
      points: "1822.69",
      num_top_tens: 8,
    },
    {
      player_id: 130876,
      player_name: "Vincent Norrman",
      position: 7,
      movement: 35,
      num_events: 4,
      num_wins: 2,
      points: "1753.35",
      num_top_tens: 2,
    },
    {
      player_id: 123697,
      player_name: "Robert Macintyre",
      position: 8,
      movement: -1,
      num_events: 20,
      num_wins: 0,
      points: "1667.14",
      num_top_tens: 6,
    },
    {
      player_id: 120460,
      player_name: "Viktor Hovland",
      position: 9,
      movement: -1,
      num_events: 6,
      num_wins: 0,
      points: "1545.58",
      num_top_tens: 2,
    },
    {
      player_id: 102271,
      player_name: "Joost Luiten",
      position: 10,
      movement: -1,
      num_events: 21,
      num_wins: 0,
      points: "1411.7",
      num_top_tens: 7,
    },
  ],
  pageCount: 15,
};
