export const leaderboard = [
  {
    player_id: 151591,
    player_name: "Collin Morikawa",
    position: 1,
    movement: 0,
    num_events: 20,
    num_wins: 2,
    points: "2,171",
    num_top_tens: 8,
  },
  {
    player_id: 102154,
    player_name: "Jordan Spieth",
    position: 2,
    movement: 0,
    num_events: 22,
    num_wins: 1,
    points: "2,139",
    num_top_tens: 9,
  },
  {
    player_id: 106366,
    player_name: "Patrick Cantlay",
    position: 3,
    movement: 0,
    num_events: 21,
    num_wins: 2,
    points: "2,056",
    num_top_tens: 5,
  },
  {
    player_id: 102313,
    player_name: "Harris English",
    position: 4,
    movement: 0,
    num_events: 23,
    num_wins: 2,
    points: "2,039",
    num_top_tens: 8,
  },
  {
    player_id: 140926,
    player_name: "Jon Rahm",
    position: 5,
    movement: 0,
    num_events: 19,
    num_wins: 1,
    points: "2,003",
    num_top_tens: 12,
  },
  {
    player_id: 136594,
    player_name: "Abraham Ancer",
    position: 6,
    movement: 0,
    num_events: 24,
    num_wins: 1,
    points: "1,926",
    num_top_tens: 7,
  },
];
